"""
Django settings for proyectoBallena project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.dirname(os.path.realpath(__file__))
PROJECT_ROOT = os.path.normpath(os.path.dirname(__file__))
DOTENV_PATH = (os.path.join(BASE_DIR, ".env") or ".env")
load_dotenv(DOTENV_PATH)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
URL=os.environ.get('APP_URL')
NAME=os.environ.get('NAME')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
DEBUG = os.environ.get('DEBUG') == 'True'

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS=os.environ.get('CSRF_TRUSTED_ORIGINS').split(',')
#django compressor
COMPRESS_ROOT = SITE_ROOT + '/templates/static'

COMPRESS_ENABLED = True

MJML_BACKEND_MODE = 'cmd'
MJML_EXEC_CMD = os.environ.get('MJML_EXEC_CMD', 'mjml')
MJML_CHECK_CMD_ON_STARTUP = True

STATICFILES_FINDERS = ('compressor.finders.CompressorFinder',)
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fontawesomefree',
    'compressor',
    'CMS',
    'Rifa',
    'pagos_banco',
    'crispy_forms',
    "crispy_bootstrap5",
    'dynamic_preferences',
    'django_crontab',
  #  'django_q',
    # comment the following line if you don't want to use user preferences
    'dynamic_preferences.users.apps.UserPreferencesConfig',
    'django_celery_beat',
    'django_celery_results',
    'mjml',
]
CRONJOBS = [
    ('*/60 * * * *', 'Rifa.cron.horario'),
    ('*/6 * * * *', 'Rifa.cron.recuperaNumeros'),
    ('*/10 * * * *', 'Rifa.cron.avisos'),
    ('0 7 * * *', 'Rifa.cron.Stats'),
    ('*/15 * * * *', 'Rifa.cron.validaFechaSorte')

    
]
PUBLIC_VIEWS = [
    'Rifa.views.Login',
]

Q_CLUSTER = {
    'orm': 'default',  # should use django's ORM and database as a broker.
    'workers': 4,
    'timeout': 30,
    'retry': 60,
    'queue_limit': 50,
    'bulk': 10,
}
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
     'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   
]
   ##  'global_login_required.GlobalLoginRequiredMiddleware',
############


CELERY_RESULT_BACKEND = "django-db"

# This configures Redis as the datastore between Django + Celery
# CELERY_BROKER_URL = 'redis://localhost:6379'
# if you out to use os.environ the config is:
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_REDIS_URL', 'redis://localhost:6379')


# this allows you to schedule items in the Django admin.
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'


##############3

SESSION_EXPIRE_SECONDS = 3600  * 24  # 1 hour
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = False

ROOT_URLCONF = 'proyectoBallena.urls'
TEMPLATE_DIR = os.path.join(CORE_DIR, "core/templates")  # ROOT dir for templates
PROJECT_PATH = os.path.abspath(os.path.dirname(__name__))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [SITE_ROOT +'/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyectoBallena.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default':{
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME':os.environ.get('DB_NAME'),
        'USER':os.environ.get('DB_USER'),
        'PASSWORD':os.environ.get('DB_PASSWORD'),
        'HOST':os.environ.get('DB_HOST'),
        'PORT':os.environ.get('DB_PORT'),
        "CONN_MAX_AGE": int(os.environ.get('DB_CONN_MAX_AGE') or "500"),
        "conn_max_age": int(os.environ.get('DB_CONN_MAX_AGE') or "500"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-ve'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True

LOGIN_URL ="/Login/"
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = SITE_ROOT + '/templates/static'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# available settings with their default values
DYNAMIC_PREFERENCES = {


    # a python attribute that will be added to model instances with preferences
    # override this if the default collide with one of your models attributes/fields
    'MANAGER_ATTRIBUTE': 'preferences',

    # The python module in which registered preferences will be searched within each app
    'REGISTRY_MODULE': 'dynamic_preferences_registry',

    # Allow quick editing of preferences directly in admin list view
    # WARNING: enabling this feature can cause data corruption if multiple users
    # use the same list view at the same time, see https://code.djangoproject.com/ticket/11313
    'ADMIN_ENABLE_CHANGELIST_FORM': False,

    # Customize how you can access preferences from managers. The default is to
    # separate sections and keys with two underscores. This is probably not a settings you'll
    # want to change, but it's here just in case
    'SECTION_KEY_SEPARATOR': '__',

    # Use this to disable auto registration of the GlobalPreferenceModel.
    # This can be useful to register your own model in the global_preferences_registry.
    'ENABLE_GLOBAL_MODEL_AUTO_REGISTRATION': True,

    # Use this to disable caching of preference. This can be useful to debug things
    'ENABLE_CACHE': True,

    # Use this to disable checking preferences names. This can be useful to debug things
    'VALIDATE_NAMES': True,
}
MEDIA_ROOT = BASE_DIR/'media'
MEDIA_URL = '/media/'

#Mail Setup

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS') == 'True'
EMAIL_PORT = int(os.environ.get('EMAIL_PORT'))
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')



TIPOS_PAGO={

    "ekiiPago":1,
    "Binance":2
}

#llaves ekipago

EKIIPAGO={
"username": "aleautos1produccion",
"platformId": 3,
"password":"#0lC%x3DvT"
}

LOGOUT_REDIRECT_URL = "Login"
SESSION_TIMEOUT_REDIRECT = 'Login'

CHINCHIN_PUBLIC=os.environ.get('CHINCHIN_PUBLIC')
CHINCHIN_PRIVATE=os.environ.get('CHINCHIN_PRIVATE')
CHINCHIN_ID=os.environ.get('CHINCHIN_ID')
CHINCHIN_URL=os.environ.get('CHINCHIN_URL')
API_KEY_CHINCHIN=os.environ.get('API_KEY_CHINCHIN')

# Banco R4 Conecta
BANCO_UUID_TOKEN = '16354fd1-afdd-4d32-8f1c-331bc39ac824'

#Logging
LOG_DIRS = ['debug', 'warning']
LOG_FILENAME = 'ballena'
for current_dir in LOG_DIRS:
    Path(os.path.join(BASE_DIR, f"logs/{current_dir}")).mkdir(exist_ok=True, parents=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format':
                '[%(asctime)s] %(levelname)s - caller=%(filename)s - %(funcName)s - Line: %(lineno)s - %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        # Handler for all log messages
        'file_all': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, f"logs/debug/{LOG_FILENAME}.log"),
            'when': 'D',
            'backupCount': 100,
            'formatter': 'standard',
        },
        # Handler for warnings and errors
        'file_warnings_errors': {
            'level': 'WARNING',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, f"logs/warning/{LOG_FILENAME}.log"),
            'when': 'D',
            'backupCount': 100,
            'formatter': 'standard',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'ballena': {
            'handlers': ['file_all', 'file_warnings_errors', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        }
    }
}

MJML_BACKEND_MODE = 'cmd'
MJML_EXEC_CMD = 'mjml'
