# Generated by Django 4.2.1 on 2024-12-08 22:19

import Rifa.utils
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Referencia', models.TextField(null=True)),
                ('FechaCompra', models.DateTimeField(null=True)),
                ('Comprobante', models.FileField(default=None, null=True, upload_to=Rifa.utils.get_file_path)),
                ('NumeroBoletos', models.IntegerField(null=True)),
                ('TotalPagado', models.FloatField(null=True)),
                ('TasaBS', models.FloatField(null=True)),
                ('MetodoPago', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3')),
                ('Estado', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1')),
                ('hash', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('recuperado', models.BooleanField(default=False)),
                ('CorreoEnviado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField()),
                ('Cedula', models.TextField()),
                ('Correo', models.EmailField(max_length=254)),
                ('Direccion', models.TextField()),
                ('NumeroTlf', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('evento', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reference', models.TextField()),
                ('currency', models.TextField(choices=[('VES', 'VES'), ('USD', 'USD')], default='USD')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paymentType', models.TextField(choices=[('P2C', 'P2C'), ('C2P', 'C2P'), ('P2Pc', 'P2Pc'), ('P2Pp', 'P2Pp'), ('P2P', 'P2P'), ('RTIc', 'RTIc'), ('RTIp', 'RTIp')], default='P2C')),
                ('customer_name', models.TextField()),
                ('customer_email', models.TextField(blank=True, null=True)),
                ('customer_phone', models.TextField()),
                ('customer_identification', models.TextField()),
                ('customer_bank', models.TextField(blank=True, null=True)),
                ('customer_account', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('branchOffice', models.TextField(blank=True, null=True)),
                ('cashRegister', models.TextField(blank=True, null=True)),
                ('seller', models.TextField(blank=True, null=True)),
                ('channel', models.TextField(choices=[('MERCHANT', 'MERCHANT'), ('POS', 'POS'), ('VPOS', 'VPOS'), ('PAYMENT_BUTTON', 'PAYMENT_BUTTON'), ('WALLET', 'WALLET'), ('WEB ', 'WEB ')], default='PAYMENT_BUTTON')),
            ],
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('Id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField()),
                ('NombreEnlace', models.TextField(null=True, unique=True)),
                ('Intervalo', models.IntegerField()),
                ('FechaSorteo', models.DateTimeField()),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('MinCompra', models.IntegerField()),
                ('MaxCompra', models.IntegerField()),
                ('RangoInicial', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('RangoFinal', models.IntegerField()),
                ('Precio', models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('Banner', models.ImageField(default=None, null=True, upload_to=Rifa.utils.get_file_path)),
                ('Descripcion', models.TextField(null=True)),
                ('Resumen', models.TextField(null=True)),
                ('Estado', models.BooleanField(default=False)),
                ('Extension', models.BooleanField(default=False)),
                ('Eliminada', models.BooleanField(default=False)),
                ('TotalNumeros', models.IntegerField(default=0)),
                ('TotalComprados', models.IntegerField(default=0)),
                ('DiasFecha', models.IntegerField(default=0)),
                ('PorcentajeActivacion', models.IntegerField(default=0)),
                ('ModoPorcentaje', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tasas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('tasa', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('dNuevo', models.IntegerField(default=0, null=True)),
                ('dRecurrente', models.IntegerField(default=0, null=True)),
                ('mNuevo', models.IntegerField(default=0, null=True)),
                ('mRecurrente', models.IntegerField(default=0, null=True)),
                ('sNuevo', models.IntegerField(default=0, null=True)),
                ('sRecurrente', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReenviosMasivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('estado', models.SmallIntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idRifa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RifaReenvio', to='Rifa.rifa')),
            ],
        ),
        migrations.CreateModel(
            name='PremiosRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField()),
                ('Descripcion', models.TextField(default=None, null=True)),
                ('Orden', models.SmallIntegerField()),
                ('FotoPremio', models.ImageField(default=None, null=True, upload_to=Rifa.utils.get_file_path)),
                ('FotoGanador', models.ImageField(default=None, null=True, upload_to=Rifa.utils.get_file_path)),
                ('idRifa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PremiosRifa', to='Rifa.rifa')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenesReservas',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateTimeField(null=True)),
                ('customer_name', models.TextField()),
                ('customer_email', models.TextField(blank=True, null=True)),
                ('customer_phone', models.TextField()),
                ('customer_identification', models.TextField()),
                ('description', models.TextField()),
                ('completada', models.BooleanField(default=False)),
                ('idRifa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RifaOrden', to='Rifa.rifa')),
            ],
        ),
        migrations.CreateModel(
            name='NumerosCompraArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numeros', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None)),
                ('idCompra', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumerosCompraArray', to='Rifa.compra')),
            ],
        ),
        migrations.CreateModel(
            name='NumerosCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.TextField()),
                ('idCompra', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumerosCompra', to='Rifa.compra')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroRifaReservadosOrdenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.TextField()),
                ('date', models.DateTimeField(null=True)),
                ('idOrden', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrdenReserva', to='Rifa.ordenesreservas')),
                ('idRifa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RifaReserva', to='Rifa.rifa')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroRifaReservados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.TextField()),
                ('date', models.DateTimeField(null=True)),
                ('idOrden', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrdenNumero', to='Rifa.ordenes')),
                ('idRifa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numReserva', to='Rifa.rifa')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroRifaDisponiblesArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numeros', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None)),
                ('idRifa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumeroRifaDisponblesArray', to='Rifa.rifa')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroRifaDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.TextField()),
                ('idRifa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumeroRifaDisponibles', to='Rifa.rifa')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroRifaCompradosArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numeros', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None)),
                ('idRifa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumeroRifaCompradosArray', to='Rifa.rifa')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroRifaComprados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.TextField()),
                ('idRifa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumeroRifaComprados', to='Rifa.rifa')),
            ],
        ),
        migrations.CreateModel(
            name='LoggerAprobadoRechazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('evento', models.TextField(null=True)),
                ('idCompra', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumerosCompraLogger', to='Rifa.compra')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagePath', models.URLField()),
                ('imageName', models.TextField()),
                ('imagePosition', models.IntegerField()),
                ('DetallesRiFA', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImagenesRifa', to='Rifa.rifa')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='idComprador',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comprador', to='Rifa.comprador'),
        ),
        migrations.AddField(
            model_name='compra',
            name='idOrden',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrdenCompra', to='Rifa.ordenes'),
        ),
        migrations.AddField(
            model_name='compra',
            name='idRifa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RifaCompra', to='Rifa.rifa'),
        ),
        migrations.AddConstraint(
            model_name='numerorifareservadosordenes',
            constraint=models.UniqueConstraint(fields=('idRifa', 'Numero'), name='unique_Compra'),
        ),
    ]
