# Generated by Django 4.2.1 on 2024-12-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifa', '0002_alter_rifa_fechasorteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifa',
            name='PorcentajeActivacion',
            field=models.FloatField(default=0),
        ),
    ]
