# Generated by Django 4.2.1 on 2025-01-18 01:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifa', '0003_alter_rifa_porcentajeactivacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='PrecioAlt',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='compra',
            name='MetodoPago',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='3'),
        ),
    ]
