# Generated by Django 4.2.1 on 2025-01-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifa', '0004_rifa_precioalt_alter_compra_metodopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='TotalPagadoAlt',
            field=models.FloatField(null=True),
        ),
    ]
