# Generated by Django 4.2.1 on 2025-01-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifa', '0005_compra_totalpagadoalt'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='Video',
            field=models.TextField(null=True),
        ),
    ]
