# Generated by Django 4.2.1 on 2025-01-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rifa', '0006_rifa_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rifa',
            name='Video',
        ),
    ]
