# Generated by Django 4.2.1 on 2025-01-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifa', '0007_remove_rifa_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='Video',
            field=models.TextField(null=True),
        ),
    ]
