# Generated by Django 4.2.1 on 2025-02-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifa', '0009_settings_compra_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='MetodoPago',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3'),
        ),
    ]
