# Generated by Django 4.2.1 on 2025-02-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifa', '0010_alter_compra_metodopago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='author',
        ),
        migrations.RemoveField(
            model_name='rifa',
            name='Video',
        ),
        migrations.AlterField(
            model_name='compra',
            name='MetodoPago',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='3'),
        ),
    ]
