# Generated by Django 4.2.1 on 2025-02-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifa', '0011_delete_settings_remove_compra_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='TotalPagadoAlt',
        ),
        migrations.RemoveField(
            model_name='rifa',
            name='PrecioAlt',
        ),
        migrations.AlterField(
            model_name='compra',
            name='MetodoPago',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3'),
        ),
    ]
