# Generated by Django 4.2.1 on 2025-02-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifa', '0015_settings_compra_totalpagadoalt_compra_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='TotalPagadoAlt',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='author',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='qr',
        ),
        migrations.RemoveField(
            model_name='rifa',
            name='PrecioAlt',
        ),
        migrations.RemoveField(
            model_name='rifa',
            name='Video',
        ),
        migrations.AlterField(
            model_name='compra',
            name='Estado',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='MetodoPago',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3'),
        ),
    ]
