# Generated by Django 4.2.1 on 2025-03-22 13:44

import Rifa.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rifa', '0018_delete_settings_remove_compra_fechaestado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(null=True, unique=True)),
                ('descripcion', models.TextField(null=True)),
                ('valor', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='FechaEstado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='TotalPagadoAlt',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compra',
            name='qr',
            field=models.FileField(default=None, null=True, upload_to=Rifa.utils.get_file_path),
        ),
        migrations.AddField(
            model_name='rifa',
            name='PrecioAlt',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AddField(
            model_name='rifa',
            name='Video',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Estado',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='MetodoPago',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3'),
        ),
    ]
