# Generated by Django 4.2.1 on 2025-04-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifa', '0023_settings_remove_usuariostats_m2nuevo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='FechaEstado',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='author',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='qr',
        ),
        migrations.RemoveField(
            model_name='rifa',
            name='Video',
        ),
        migrations.AddField(
            model_name='usuariostats',
            name='m2Nuevo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuariostats',
            name='m2Recurrente',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuariostats',
            name='m3Nuevo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuariostats',
            name='m3Recurrente',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Estado',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='MetodoPago',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='3'),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='Correo',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
