# Generated by Django 4.2.1 on 2025-04-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifa', '0025_settings_remove_usuariostats_m2nuevo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifa',
            name='Extension',
            field=models.BooleanField(default=True),
        ),
    ]
